version: "3.7"

services:
    discord:
        build: ./
        container_name: "discord_bot"
        env_file:
            - .env

    mongo:
        image: mongo
        container_name: "docker_bot_mongo"
        environment:
            MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
            MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
        volumes:    
            - ./.data/db:/data/db:delegated

      # If want to accessible outside of docker
      # ports:
      #     - "27017:27017"
